# Generated by Django 4.2 on 2023-04-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_article_title_alter_article_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_text',
            new_name='text',
        ),
    ]
