# Generated by Django 4.2 on 2023-04-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_article_created_at_alter_article_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
